// Celestia: all educational content and interaction data live in one portable object.
const planets = [
  {name:'Mercury',type:'TERRESTRIAL PLANET',size:10,orbit:145,speed:'8s',bg:'radial-gradient(circle at 32% 28%,#e7d7bf,#9b8c80 46%,#493f3d)',glow:'#ccb7a0',tag:'The swiftest world in our solar system.',diameter:'4,879 km',mass:'3.30 × 10²³ kg',gravity:'3.7 m/s²',temp:'167°C',distance:'57.9 million km',day:'58.6 Earth days',year:'88 Earth days',moons:'0',description:'Mercury is the smallest and innermost planet. Its cratered surface endures the solar system’s most dramatic swings between daytime heat and nighttime cold.',fun:'A single solar day on Mercury lasts 176 Earth days—twice as long as its year.',facts:['It has a very thin, constantly replenished exosphere.','Water ice survives in permanently shadowed polar craters.']},
  {name:'Venus',type:'TERRESTRIAL PLANET',size:16,orbit:190,speed:'12s',bg:'radial-gradient(circle at 28% 28%,#fff3b1,#e6a449 47%,#94512c)',glow:'#f6b86d',tag:'A beautiful world beneath a crushing sky.',diameter:'12,104 km',mass:'4.87 × 10²⁴ kg',gravity:'8.87 m/s²',temp:'464°C',distance:'108.2 million km',day:'243 Earth days',year:'225 Earth days',moons:'0',description:'Venus is Earth’s near-twin in size, but its thick carbon-dioxide atmosphere creates an extreme runaway greenhouse effect.',fun:'Venus spins backward: on Venus, the Sun rises in the west.',facts:['Its atmospheric pressure is about 90 times Earth’s.','It is the hottest planet, despite Mercury being closer to the Sun.']},
  {name:'Earth',type:'TERRESTRIAL PLANET',size:18,orbit:240,speed:'16s',bg:'radial-gradient(circle at 32% 27%,#c7f4ff 0 6%,#3c9ce8 12% 32%,#2366be 48%,#10356f 75%)',glow:'#59bfff',tag:'Our blue oasis in the vast dark.',diameter:'12,742 km',mass:'5.97 × 10²⁴ kg',gravity:'9.81 m/s²',temp:'15°C',distance:'149.6 million km',day:'24 hours',year:'365.25 days',moons:'1',description:'Earth is the only known world to host life. Liquid surface water, a protective atmosphere, and a remarkably stable climate make it our home planet.',fun:'Earth is not a perfect sphere—it bulges slightly around its equator.',facts:['About 71% of Earth’s surface is covered by ocean.','Its magnetic field helps protect life from solar wind.']},
  {name:'Mars',type:'TERRESTRIAL PLANET',size:14,orbit:294,speed:'21s',bg:'radial-gradient(circle at 30% 26%,#f5b080,#c9603e 45%,#752d25 83%)',glow:'#ed755a',tag:'The red frontier, sculpted by wind and time.',diameter:'6,779 km',mass:'6.42 × 10²³ kg',gravity:'3.71 m/s²',temp:'−65°C',distance:'227.9 million km',day:'24.6 hours',year:'687 Earth days',moons:'2',description:'Mars is a cold desert world with a thin atmosphere. Its ancient river valleys and polar ice caps make it a compelling destination for exploration.',fun:'Olympus Mons on Mars is the largest volcano in the solar system.',facts:['Mars has the solar system’s largest canyon, Valles Marineris.','Its two small moons are Phobos and Deimos.']},
  {name:'Jupiter',type:'GAS GIANT',size:43,orbit:365,speed:'34s',bg:'repeating-linear-gradient(170deg,#e6c9a1 0 6px,#b6774e 7px 12px,#f2ddbb 13px 19px,#9d563d 20px 27px)',glow:'#dba56f',tag:'The colossal guardian of the outer worlds.',diameter:'139,820 km',mass:'1.90 × 10²⁷ kg',gravity:'24.79 m/s²',temp:'−110°C',distance:'778.5 million km',day:'9.9 hours',year:'11.86 Earth years',moons:'95',description:'Jupiter is the largest planet and a swirling sphere of hydrogen and helium. Its Great Red Spot is a storm larger than Earth.',fun:'Jupiter has the shortest day of all the planets.',facts:['It has a faint ring system and a powerful magnetic field.','Its four largest moons were discovered by Galileo in 1610.']},
  {name:'Saturn',type:'GAS GIANT',size:37,orbit:450,speed:'47s',bg:'linear-gradient(155deg,#f8e3a5,#d4b46e 42%,#9e7e4c 77%)',glow:'#e8ce88',tag:'The ringed jewel of the solar system.',diameter:'116,460 km',mass:'5.68 × 10²⁶ kg',gravity:'10.44 m/s²',temp:'−140°C',distance:'1.43 billion km',day:'10.7 hours',year:'29.45 Earth years',moons:'146',description:'Saturn is a majestic gas giant known for its spectacular rings. They are made mostly of ice particles, from dust-sized grains to house-sized chunks.',fun:'Saturn would float in water: its average density is lower than water’s.',facts:['Its rings extend hundreds of thousands of kilometres but are remarkably thin.','Titan, its largest moon, has lakes and rivers of liquid methane.']},
  {name:'Uranus',type:'ICE GIANT',size:26,orbit:530,speed:'60s',bg:'radial-gradient(circle at 30% 25%,#d2ffff,#82d1dc 48%,#397c99)',glow:'#8ce7ed',tag:'An icy world rolling through the darkness.',diameter:'50,724 km',mass:'8.68 × 10²⁵ kg',gravity:'8.69 m/s²',temp:'−195°C',distance:'2.87 billion km',day:'17.2 hours',year:'84 Earth years',moons:'28',description:'Uranus is an ice giant with a pale blue colour from methane in its atmosphere. It rotates almost entirely on its side.',fun:'Its extreme tilt produces seasons that each last more than 20 Earth years.',facts:['Uranus was the first planet discovered with a telescope.','It has 13 known faint rings.']},
  {name:'Neptune',type:'ICE GIANT',size:25,orbit:610,speed:'75s',bg:'radial-gradient(circle at 30% 25%,#87caff,#286fda 46%,#123886)',glow:'#508eff',tag:'The wind-swept blue world at the edge.',diameter:'49,244 km',mass:'1.02 × 10²⁶ kg',gravity:'11.15 m/s²',temp:'−200°C',distance:'4.50 billion km',day:'16.1 hours',year:'164.8 Earth years',moons:'16',description:'Neptune is the outermost major planet, a dynamic ice giant wrapped in the fastest winds measured anywhere in the solar system.',fun:'Neptune completed its first orbit since discovery in 2011.',facts:['Winds in its atmosphere can exceed 2,000 km/h.','Its largest moon Triton orbits in the opposite direction to Neptune’s rotation.']}
];
const solarSystem = document.querySelector('#solarSystem');
const modal = document.querySelector('#planetModal');
let zoom = 1, drag = {active:false,x:0,y:0,dx:0,dy:0};
function renderSystem(){ solarSystem.innerHTML='<div class="sun" role="img" aria-label="The Sun"></div><div class="asteroid-belt" aria-label="Asteroid belt"></div>'; planets.forEach((p,i)=>{ const openPlanetDetails=()=>cinematicOpen(p); const orbit=document.createElement('div'); orbit.className=`orbit ${p.name.toLowerCase()}`; orbit.style.cssText=`--orbit:${p.orbit}px;--speed:${p.speed};--planet-size:${p.size}px;--hit-size:${Math.max(p.size,44)}px`; const wrap=document.createElement('div'); wrap.className='planet-wrap'; wrap.dataset.distance=`${p.distance} from Sun`; const planet=document.createElement('button'); planet.type='button'; planet.className='planet'; planet.dataset.planet=p.name; planet.style.cssText=`--planet-bg:${p.bg};--glow:${p.glow}`; planet.setAttribute('aria-label',`Open ${p.name} information panel, ${p.distance} from the Sun`); planet.addEventListener('click',openPlanetDetails); wrap.append(planet); orbit.append(wrap); const label=document.createElement('button'); label.type='button'; label.className='planet-label'; label.dataset.planet=p.name; label.textContent=p.name; label.style.setProperty('--orbit',p.orbit+'px'); label.setAttribute('aria-label',`Open ${p.name} information panel`); label.addEventListener('click',openPlanetDetails); solarSystem.append(orbit,label); }); }
function openModal(p){ modal.classList.toggle('earth-dossier',p.name==='Earth'); document.querySelector('#modalName').textContent=p.name; document.querySelector('#modalType').textContent=p.name==='Earth'?'HOME PLANET · TERRESTRIAL PLANET':p.type; document.querySelector('#modalTagline').textContent=p.tag; document.querySelector('#modalDescription').textContent=p.description; document.querySelector('#modalFunFact').textContent=p.fun; const visual=document.querySelector('#modalPlanet'); visual.style.cssText=`--planet-bg:${p.bg};--glow:${p.glow}`; const labels={diameter:'Diameter',mass:'Mass',gravity:'Gravity',temp:'Avg. temperature',distance:'Distance from Sun',day:'Length of day',year:'Length of year',moons:'Moons'}; document.querySelector('#facts').innerHTML=Object.entries(labels).map(([key,label])=>`<div><dt>${label}</dt><dd>${p[key]}</dd></div>`).join(''); document.querySelector('#interestingFacts').innerHTML=p.facts.map(f=>`<li>${f}</li>`).join(''); modal.hidden=false; document.body.style.overflow='hidden'; document.querySelector('.modal-close').focus(); }
function closeModal(){modal.hidden=true;document.body.style.overflow='';}
document.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModal)); document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden) closeModal();});
function setView(){solarSystem.style.transform=`translate(calc(-50% + ${drag.dx}px), calc(-50% + ${drag.dy}px)) scale(${zoom})`;}
document.querySelector('#zoomIn').onclick=()=>{zoom=Math.min(1.65,zoom+.15);setView()}; document.querySelector('#zoomOut').onclick=()=>{zoom=Math.max(.65,zoom-.15);setView()}; document.querySelector('#resetView').onclick=()=>{zoom=1;drag.dx=drag.dy=0;setView()};
const card=document.querySelector('#systemCard'); card.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag.active=true;drag.x=e.clientX-drag.dx;drag.y=e.clientY-drag.dy;card.setPointerCapture(e.pointerId)}); card.addEventListener('pointermove',e=>{if(!drag.active)return;drag.dx=e.clientX-drag.x;drag.dy=e.clientY-drag.y;setView()}); card.addEventListener('pointerup',()=>drag.active=false);
const stars=document.querySelector('#stars') || document.createElement('div'); for(let i=0;i<260;i++){const s=document.createElement('i');s.className='star';s.style.cssText=`left:${Math.random()*100}%;top:${Math.random()*100}%;--s:${Math.random()*2.3+.5}px;--o:${Math.random()*.7+.15};--t:${Math.random()*3+1.2}s;animation-delay:-${Math.random()*4}s`;stars.append(s)}
function shooting(){const s=document.createElement('i');s.className='shooting-star';s.style.cssText=`left:${20+Math.random()*75}%;top:${Math.random()*55}%;`;document.querySelector('#shootingStars').append(s);setTimeout(()=>s.remove(),1400);setTimeout(shooting,3500+Math.random()*6000)}setTimeout(shooting,2200);
document.addEventListener('pointermove',e=>{document.querySelector('#cursorGlow').style.left=e.clientX+'px';document.querySelector('#cursorGlow').style.top=e.clientY+'px';});
renderSystem(); window.addEventListener('load',()=>setTimeout(()=>document.querySelector('#loader').classList.add('hide'),650));

// Canvas starfield: one animation loop instead of hundreds of DOM updates.
const canvas=document.querySelector('#starCanvas'),ctx=canvas.getContext('2d');let canvasStars=[];
function sizeCanvas(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);canvasStars=Array.from({length:Math.min(360,Math.floor(innerWidth/4))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.25+.18,a:Math.random(),v:Math.random()*.018+.004}));}function drawStars(t){ctx.clearRect(0,0,innerWidth,innerHeight);canvasStars.forEach(s=>{const a=.25+Math.abs(Math.sin(t*s.v))*.7;ctx.fillStyle=`rgba(210,232,255,${a})`;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill();});requestAnimationFrame(drawStars)}sizeCanvas();addEventListener('resize',sizeCanvas);requestAnimationFrame(drawStars);
// Mouse parallax keeps the far nebulae and system gently responsive.
document.addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*16,y=(e.clientY/innerHeight-.5)*16;document.querySelector('.nebula-a').style.transform=`translate(${x}px,${y}px)`;document.querySelector('.nebula-b').style.transform=`translate(${-x}px,${-y}px)`});
function comet(){const c=document.createElement('i');c.className='comet';c.style.cssText=`left:${80+Math.random()*35}%;top:${Math.random()*30}%;`;document.querySelector('#shootingStars').append(c);setTimeout(()=>c.remove(),3000);setTimeout(comet,9000+Math.random()*9000)}setTimeout(comet,5000);
// Cinematic focus is deliberately brief so details remain accessible and fast.
function cinematicOpen(p){zoom=Math.min(1.65,zoom+.35);setView();setTimeout(()=>{openModal(p);zoom=Math.max(.65,zoom-.35);setView()},380)}
// Educational colour palette toggle.
document.querySelector('#modeToggle').addEventListener('click',e=>{const on=document.body.classList.toggle('educational');e.currentTarget.setAttribute('aria-pressed',on);e.currentTarget.textContent=on?'Realistic mode':'Color mode'});
// Optional Web Audio drone: it starts only after an explicit user gesture.
let audioCtx,ambientGain;document.querySelector('#soundToggle').addEventListener('click',e=>{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();ambientGain=audioCtx.createGain();ambientGain.gain.value=.018;ambientGain.connect(audioCtx.destination);[55,82.41].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=i?'sine':'triangle';o.frequency.value=f;g.gain.value=i?.15:.1;o.connect(g).connect(ambientGain);o.start()});}const on=e.currentTarget.getAttribute('aria-pressed')!=='true';ambientGain.gain.setTargetAtTime(on?.018:0,audioCtx.currentTime,.08);e.currentTarget.setAttribute('aria-pressed',on);e.currentTarget.textContent=on?'Sound on':'Sound off'});
// Side-by-side comparison.
const selectA=document.querySelector('#compareA'),selectB=document.querySelector('#compareB');[selectA,selectB].forEach((s,i)=>{s.innerHTML=planets.map(p=>`<option value="${p.name}" ${p.name===(i?'Jupiter':'Earth')?'selected':''}>${p.name}</option>`).join('');s.addEventListener('change',renderComparison)});function renderComparison(){const a=planets.find(p=>p.name===selectA.value),b=planets.find(p=>p.name===selectB.value),fields=[['Diameter','diameter'],['Gravity','gravity'],['Length of day','day'],['Length of year','year'],['Moons','moons'],['Average temperature','temp']];document.querySelector('#comparison').innerHTML=`<div class="compare-row"><strong>Property</strong><strong>${a.name}</strong><strong>${b.name}</strong></div>`+fields.map(([l,k])=>`<div class="compare-row"><span>${l}</span><span>${a[k]}</span><span>${b[k]}</span></div>`).join('');}renderComparison();document.querySelector('#compareOpen').onclick=()=>document.querySelector('#comparePanel').hidden=false;document.querySelector('#compareClose').onclick=()=>document.querySelector('#comparePanel').hidden=true;
// Auto tour moves the camera and introduces every world in sequence.
let touring=false,tourTimer;const tourButton=document.querySelector('#tourToggle'),caption=document.querySelector('#tourCaption');function stopTour(){touring=false;clearTimeout(tourTimer);caption.classList.remove('visible');tourButton.textContent='Start auto tour';zoom=1;drag.dx=drag.dy=0;setView()}function nextTour(i=0){if(!touring)return;if(i>=planets.length){stopTour();return}const p=planets[i];zoom=1.45;drag.dx=((i%2)?-1:1)*(45+i*6);drag.dy=(i-3)*8;setView();caption.textContent=`${p.name} — ${p.tag}`;caption.classList.add('visible');tourTimer=setTimeout(()=>nextTour(i+1),3200)}tourButton.onclick=()=>{if(touring)stopTour();else{touring=true;tourButton.textContent='End auto tour';nextTour()}};

// Contributor panel keeps the contribution invitation useful even before a repository URL is configured.
const contributorCard=document.querySelector('#contributorCard');document.querySelector('#contributorButton').onclick=()=>{contributorCard.hidden=false;document.querySelector('#contributorClose').focus()};document.querySelector('#contributorClose').onclick=()=>contributorCard.hidden=true;document.querySelector('#copyCommand').onclick=async e=>{const command=e.currentTarget.dataset.command;try{await navigator.clipboard.writeText(command);document.querySelector('#copyStatus').textContent='Starter command copied — replace the URL, then launch.'}catch{document.querySelector('#copyStatus').textContent=command}}
